improvement: memudahkan pencarian pelajaran dan nomor peserta
shellrean-dev/exo-cbt-service pull request #6
Opened 2024-02-25 14:14 UTC by bzy39

2024-03-02 14:18 UTC, shellrean commented
Oke, jadi nanti hasilnya adalah tiap tiap kode banksoal akan diikuti dengan mata pelajaran?
karena kalau menurut saya lebih baik kalau kode itu udah mewakili mata pelajaran. misalnya kode matematika maka biikin banksoal dengan kode MTUTS01

2024-03-02 23:43 UTC, bzy39 commented
agar tidak perlu menghapal kode pelajaran.

2024-03-03 01:30 UTC, shellrean requested changes

2024-03-03 01:30 UTC, shellrean commented on app/Http/Controllers/Api/Gateway/BanksoalGatewayController.php
> +                DB::Raw("CONCAT(t_1.nama, ' | ', t_0.kode_banksoal) AS kode_banksoal")
ini diganti aja ke 
Kode banksoal | matpel

supaya kalau panjang, yang kepotong nama matpel bukan kode

2024-03-03 01:30 UTC, shellrean commented on app/Http/Controllers/Api/Gateway/MatpelGatewayController.php
> +                DB::Raw("CONCAT(nama, ' | ', kode_mapel) AS nama")
ini juga sama, ganti ke kode_mapel | nama

2024-03-03 10:21 UTC, shellrean approved these changes

2024-03-03 10:22 UTC, merged